ALTER TABLE public.follows ENABLE ROW LEVEL SECURITY; 
ALTER TABLE public.hashtags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.likes ENABLE ROW LEVEL SECURITY;   
ALTER TABLE public.post_hashtags ENABLE ROW LEVEL SECURITY;   
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;   
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;      